CREATE TABLE USERS (
 UserID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 EMAIL VARCHAR(50),
 PASSWORD VARCHAR(50),
 FirstName VARCHAR(50),
 LastName VARCHAR(50)
 );

 CREATE TABLE CLIENTS (
    ClientID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    EMAIL VARCHAR(50),
    PHONE VARCHAR(50)
 );

 CREATE TABLE JOBS(
    JobID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Address1 VARCHAR(50),
    Address2 VARCHAR(50),
    City VARCHAR(50),
    State VARCHAR(14),
    Zip INT,
    ClientID INT
 );

 CREATE TABLE DOCUMENTS (
    DocID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FilePath VARCHAR(50),
    FileName VARCHAR(50),
    ClientID INT,
    JobID INT
 );

  CREATE TABLE PICTURES (
    PicID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FilePath VARCHAR(50),
    FileName VARCHAR(50),
    ClientID INT,
    JobID INT
 );

  CREATE TABLE PRODUCTS (
    ProdID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50),
    Price DECIMAL(10,2),
    ClientID INT,
    JobID INT
 );

 CREATE TABLE MILAGE (
    MilageID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Beginning INT,
    Ending INT,
    Date DATE,
    UserID INT
 );